In [1]:
import os
import xarray as xr 
import pandas as pd
from math import floor
from datetime import datetime

def floorQuarter(x):
    return (floor(x * 4) / 4.0)

In [3]:
xr.set_options(display_style="html")
# lectura de archivo .nc
data = xr.open_dataset('../descargas/mercatorglorys12v1_gl12_mean_20150527_R20150603__filtrados.nc')
# xarray a dataFrame
dfC= data.to_dataframe()
# elimino los indices para modificar las fechas
dfC = dfC.reset_index()
# elimino la hora de la fechas
dfC['time'] = dfC['time'].dt.strftime('%Y-%m-%d')
# se redondea las coordnadas a un cuarto de grado para tener la misma precision que el dataframe de los avistamientos
dfC["latitude_red"] = dfC.latitude.map(floorQuarter)
dfC["longitude_red"] = dfC.longitude.map(floorQuarter)
# vuelvo a generar los indices
#dfC = dfC.set_index(["depth","latitude","longitude"])
dfC = dfC.set_index(["longitude","latitude"])
dfC

,,depth,time,mlotst,zos,bottomT,thetao,so,uo,vo,latitude_red,longitude_red
longitude,latitude,,,,,,,,,,,
-120.000000,-60.0,0.494025,2015-05-27,119.785156,-1.171300,0.123875,1.661276,33.851131,0.220344,0.083010,-60.0,-120.00
-119.916664,-60.0,0.494025,2015-05-27,119.785156,-1.177709,0.107761,1.653217,33.851131,0.213630,0.050661,-60.0,-120.00
-119.833336,-60.0,0.494025,2015-05-27,119.785156,-1.182287,0.111423,1.648090,33.851131,0.206305,0.018311,-60.0,-120.00
-119.750000,-60.0,0.494025,2015-05-27,119.785156,-1.185034,0.112156,1.633442,33.849606,0.198981,-0.013428,-60.0,-119.75
-119.666664,-60.0,0.494025,2015-05-27,119.785156,-1.185339,0.109959,1.630512,33.849606,0.192267,-0.045778,-60.0,-119.75
...,...,...,...,...,...,...,...,...,...,...,...,...
-60.333332,-10.0,9.572997,2015-05-27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-10.0,-60.50
-60.250000,-10.0,9.572997,2015-05-27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-10.0,-60.25
-60.166668,-10.0,9.572997,2015-05-27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-10.0,-60.25
-60.083332,-10.0,9.572997,2015-05-27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-10.0,-60.25
-60.000000,-10.0,9.572997,2015-05-27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-10.0,-60.00

In [29]:
#data.sel({'longitude':[-45.16558675]})
data

<xarray.Dataset>
Dimensions:    (depth: 3, latitude: 601, longitude: 721, time: 1)
Coordinates:
  * longitude  (longitude) float32 -120.0 -119.916664 ... -60.083332 -60.0
  * latitude   (latitude) float32 -60.0 -59.916668 ... -10.083333 -10.0
  * depth      (depth) float32 0.494025 5.078224 9.572997
  * time       (time) datetime64[ns] 2015-05-27T12:00:00
Data variables:
    mlotst     (time, latitude, longitude) float32 119.78516 119.78516 ... nan
    zos        (time, latitude, longitude) float32 -1.1713004 -1.1777092 ... nan
    bottomT    (time, latitude, longitude) float32 0.123874664 ... nan
    thetao     (time, depth, latitude, longitude) float32 1.6612759 ... nan
    so         (time, depth, latitude, longitude) float32 33.85113 ... nan
    uo         (time, depth, latitude, longitude) float32 0.22034363 ... nan
    vo         (time, depth, latitude, longitude) float32 0.083010346 ... nan
Attributes:
    title:              daily mean fields from Global Ocean Physics Analysis ...
    easting:            longitude
    northing:           latitude
    history:            2017/10/11 08:29:27 MERCATOR OCEAN Netcdf creation
    source:             MERCATOR GLORYS12V1
    institution:        MERCATOR OCEAN
    references:         http://www.mercator-ocean.fr
    comment:            CMEMS product
    Conventions:        CF-1.4
    domain_name:        GL12
    field_type:         mean
    field_date:         2015-05-27 00:00:00
    field_julian_date:  23887.0
    julian_day_unit:    days since 1950-01-01 00:00:00
    forecast_range:     0-day_forecast
    forecast_type:      hindcast
    bulletin_date:      2015-06-03 00:00:00
    bulletin_type:      operational
    longitude_min:      -180.0
    longitude_max:      179.91667
    latitude_min:       -80.0
    latitude_max:       90.0
    z_min:              0.494025
    z_max:              5727.917

In [50]:
datos1 = data.sel({'latitude':[-42.75],'longitude':[-74.25],'time':[datetime.strptime('2015-05-27', '%Y-%m-%d')]},method='nearest')
datos = datos1.to_dataframe()
datos

,,,,mlotst,zos,bottomT,thetao,so,uo,vo
depth,latitude,longitude,time,,,,,,,
0.494025,-42.75,-74.25,2015-05-27 12:00:00,52.339249,0.103763,12.725577,12.726310,33.355206,0.036012,-0.106815
5.078224,-42.75,-74.25,2015-05-27 12:00:00,52.339249,0.103763,12.725577,12.726310,33.355206,0.029298,-0.079958
9.572997,-42.75,-74.25,2015-05-27 12:00:00,52.339249,0.103763,12.725577,12.725577,33.355206,0.023804,-0.067141

In [22]:
dff = dfC.reset_index()
dff = dff[['latitude','longitude']]
dff = dff.loc[::500]
dff.to_excel('./coordenadas.xlsx')

In [35]:
# importo el excel
df = pd.read_excel('./avistamientos.xlsx')
# relleno celdas vacias por su respectivas coordenadas
df = df.fillna(method= 'ffill',axis=0)
# cojo los datos que nos interesan
df = df[['Lat_floor', 'Long_floor',"Fecha",'Media_Playas']]
# renombro columnas
df = df.rename(columns={"Media_Playas": "Avistamientos", "Lat_floor": "latitude", "Long_floor": "longitude", "Fecha":"time"})
# elimino indices
dfA =  df.reset_index()
# transforma date time a str para tener el mismo formato en los dos df
dfA.info()
#dfA['time'] = dfA['time'].dt.strftime('%Y-%m-%d')
#establezco indices
dfA.info()
dfA = dfA[["latitude","longitude","time","Avistamientos"]]
dfA = dfA.set_index(["latitude","longitude","time"])
dfA.info()
dfA

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 438 entries, 0 to 437
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   index          438 non-null    int64
 1   latitude       438 non-null    float64
 2   longitude      438 non-null    float64
 3   time           438 non-null    datetime64[ns]
 4   Avistamientos  438 non-null    float64
dtypes: datetime64[ns](1), float64(3), int64(1)
memory usage: 17.2 KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 438 entries, 0 to 437
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   index          438 non-null    int64
 1   latitude       438 non-null    float64
 2   longitude      438 non-null    float64
 3   time           438 non-null    datetime64[ns]
 4   Avistamientos  438 non-null    float64
dtypes: datetime64[ns](1), float64(3), int64(1)
memory usage: 17.2 KB
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 438 entries, (-42.75, -74.25, Timestamp('2015-05-27 00:00:00')) to (-18.5, -70.5, Timestamp('2015-08-18 00:00:00'))
Data columns (total 1 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Avistamientos  438 non-null    float64
dtypes: float64(1)
memory usage: 7.4 KB

                               Avistamientos
latitude longitude time
-42.75   -74.25    2015-05-27            1.0
-42.00   -74.00    2014-06-04            1.0
         -73.75    2015-05-23            1.0
-41.75   -73.75    2015-06-10           20.0
                   2015-06-11          151.0
...                                      ...
-18.50   -70.50    2014-05-01            1.0
                   2014-05-10           15.0
                   2014-07-18            1.0
                   2014-08-17            1.0
                   2015-08-18            1.0

[438 rows x 1 columns]

In [9]:
# Genera excel con las coordenadas de las playas
dffA = dfA.reset_index()
dffA = dffA[['latitude','longitude']]
dffA.to_excel('./playas.xlsx')

In [6]:
#df = pd.merge(dfC,dfA,on=["latitude","longitude","time"])
df = dfC.join(dfA)
#df.head(20)

In [45]:
df = pd.DataFrame()
df['col1'] = ['hola','adios','hastaluego']
df['col2'] = ['hola','adios','hastaluego']
# df = df.set_index(['col1'])
df[['col1','col2']]
df.loc[1,['col1','col2']] = ['columna1','columan2']
df['col1']

0          hola
1      columna1
2    hastaluego
Name: col1, dtype: object

In [62]:
listado_archivos = os.listdir('../descargas')
Fecha = '20140501'
texto ='_{}_'.format(str(Fecha).split()[0].replace('-',''))
archivo = [x for x in listado_archivos if str(texto) in x]
# cargo el archivo
data = xr.open_dataset('../descargas/{}'.format(archivo[0]))
xr_sel = data.sel({'latitude':-25.5,'longitude':-70.5},method='nearest')
a = xr_sel.to_dataframe()
a

,,longitude,latitude,mlotst,zos,bottomT,thetao,so,uo,vo
depth,time,,,,,,,,,
0.494025,2014-05-01 12:00:00,-70.5,-25.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5.078224,2014-05-01 12:00:00,-70.5,-25.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9.572997,2014-05-01 12:00:00,-70.5,-25.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN